name = "FastDysonSolver"
authors = ["BaptisteLamic"]

[deps]
AppleAccelerate = "13e28ba4-7ad8-5781-acae-3021b1ed3924"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HssMatrices = "0c1fde87-e0ea-49d6-ac2f-89b694f639e1"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
NonEquilibriumGreenFunction = "23f16301-fe5b-45da-b088-f1dd23511803"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
QuanticsTCI = "b11687fd-3a1c-4c41-97d0-998ab401d50e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Richardson = "708f8203-808e-40c0-ba2d-98a6953ed40d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymbolicNumericIntegration = "78aadeae-fbc0-11eb-17b6-c7ec0477ba9e"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"

[compat]
DrWatson = "2"
NonEquilibriumGreenFunction = "0.2"
julia = "1"
